apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd
    tag: alpine
  name: httpd
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
      tag: alpine
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: httpd
        tag: alpine
    spec:
      containers:
      - image: httpd
        imagePullPolicy: IfNotPresent
        name: httpd-example
